root: datasets
dataset_name: cute
task: str
download_links:
  - https://download.openmmlab.com/mmocr/data/mixture/ct80/timage.tar.gz.gz
  - https://download.openmmlab.com/mmocr/data/1.x/recog/ct80/textrecog_test.json
filenames:
  - data.tar.gz
  - anns.json
check_validity: true
max_len: 800