root: datasets
dataset_name: icdar13
task: str
download_links: 
  - https://rrc.cvc.uab.es/downloads/Challenge2_Training_Task3_Images_GT.zip
  - https://rrc.cvc.uab.es/downloads/Challenge2_Test_Task3_Images.zip
  - https://rrc.cvc.uab.es/downloads/Challenge2_Test_Task3_GT.txt
filenames:
  - train_images_anns.zip
  - test.zip
  - test_anns.txt
check_validity: false
max_len: 800