root: datasets
dataset_name: icdar15
task: str
download_links: 
  - https://rrc.cvc.uab.es/downloads/ch2_training_images.zip
  - https://rrc.cvc.uab.es/downloads/ch2_training_localization_transcription_gt.zip
filenames:
  - train_images.zip
  - train_localization_transcription.zip
check_validity: false
max_len: 800