root: datasets
dataset_name: naf
task: str
download_links:
  - https://github.com/herobd/NAF_dataset/releases/download/v1.0/labeled_images.tar.gz
  - https://github.com/herobd/NAF_dataset/archive/refs/heads/master.zip
filenames:
  - data.tar.gz
  - labels.zip
check_validity: true
max_len: 800