root: datasets
dataset_name: synthtext
task: str
download_links:
  - https://academictorrents.com/download/2dba9518166cbd141534cbf381aa3e99a087e83c.torrent
filenames:
  - synthtext.torrent
check_validity: true
max_len: 800