root: data
task: str
download_links:
  - https://drive.usercontent.google.com/download?id=1qO1d3-3dIwQVZ-oBcTxCYEMuxbSPG7Pq&authuser=0&confirm=t
  # COCOTextv1.4
  - https://vision.cornell.edu/se3/wp-content/uploads/2019/05/COCO_Text.zip
  - http://images.cocodataset.org/zips/train2014.zip
filenames:
  - data.zip
  - COCOText_v1_4_labels.zip
  - COCOText_v1_4.zip
processors:
  - null
  - null
  - coco_text_converter:
    ann_file: COCO_Text.json
    output_dir: data/test/COCOv1.4
    use_split_naming: false
check_validity: false